<?php

namespace ContainerQGgnTIx;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_Errored_1bOlI6XService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored.1bOlI6X' shared service.
     *
     * @return \App\Repository\KidsRepository
     */
    public static function do($container, $lazyLoad = true)
    {
        $container->throw('Cannot determine controller argument for "App\\Controller\\APIUserController::getPostsByKidId()": the $KidsRepository argument is type-hinted with the non-existent class or interface: "App\\Repository\\KidsRepository".');
    }
}
