<?php

namespace ContainerQGgnTIx;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_Errored_CKB2NcService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored._cKB2Nc' shared service.
     *
     * @return \App\Repository\MediaObjectRepository
     */
    public static function do($container, $lazyLoad = true)
    {
        $container->throw('Cannot determine controller argument for "App\\Controller\\APIUserController::getKidsBytag()": the $MediaObjectRepository argument is type-hinted with the non-existent class or interface: "App\\Repository\\MediaObjectRepository".');
    }
}
