<?php

namespace ContainerQGgnTIx;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_VvJBn7Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.vv_jBn7' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.vv_jBn7'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'KidsRepository' => ['privates', '.errored.AH5q0a7', NULL, 'Cannot determine controller argument for "App\\Controller\\APIUserController::getKidsById()": the $KidsRepository argument is type-hinted with the non-existent class or interface: "App\\Repository\\KidsRepository".'],
            'MediaObjectRepository' => ['privates', '.errored.ygR6OxO', NULL, 'Cannot determine controller argument for "App\\Controller\\APIUserController::getKidsById()": the $MediaObjectRepository argument is type-hinted with the non-existent class or interface: "App\\Repository\\MediaObjectRepository".'],
            'UserRapository' => ['privates', 'App\\Repository\\UserRepository', 'getUserRepositoryService', true],
        ], [
            'KidsRepository' => '?',
            'MediaObjectRepository' => '?',
            'UserRapository' => 'App\\Repository\\UserRepository',
        ]);
    }
}
