<?php

namespace ContainerQGgnTIx;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_Vpo0qE1Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.Vpo0qE1' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.Vpo0qE1'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'MediaObjectRepository' => ['privates', '.errored.y8OqGmM', NULL, 'Cannot determine controller argument for "App\\Controller\\APIUserController::getUserById()": the $MediaObjectRepository argument is type-hinted with the non-existent class or interface: "App\\Repository\\MediaObjectRepository".'],
            'UserRapository' => ['privates', 'App\\Repository\\UserRepository', 'getUserRepositoryService', true],
        ], [
            'MediaObjectRepository' => '?',
            'UserRapository' => 'App\\Repository\\UserRepository',
        ]);
    }
}
