<?php

namespace ContainerQGgnTIx;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_JOMDu52Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.JOMDu52' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.JOMDu52'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'KidsRepository' => ['privates', '.errored.1bOlI6X', NULL, 'Cannot determine controller argument for "App\\Controller\\APIUserController::getPostsByKidId()": the $KidsRepository argument is type-hinted with the non-existent class or interface: "App\\Repository\\KidsRepository".'],
            'MediaObjectRepository' => ['privates', '.errored.od6.jzl', NULL, 'Cannot determine controller argument for "App\\Controller\\APIUserController::getPostsByKidId()": the $MediaObjectRepository argument is type-hinted with the non-existent class or interface: "App\\Repository\\MediaObjectRepository".'],
            'PostRepository' => ['privates', 'App\\Repository\\PostRepository', 'getPostRepositoryService', true],
        ], [
            'KidsRepository' => '?',
            'MediaObjectRepository' => '?',
            'PostRepository' => 'App\\Repository\\PostRepository',
        ]);
    }
}
