<?php

namespace ContainerQGgnTIx;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getCreateMediaObjectActionService extends App_KernelDevDebugContainer
{
    /**
     * Gets the public 'App\Controller\CreateMediaObjectAction' shared autowired service.
     *
     * @return \App\Controller\CreateMediaObjectAction
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'src'.\DIRECTORY_SEPARATOR.'Controller'.\DIRECTORY_SEPARATOR.'CreateMediaObjectAction.php';

        return $container->services['App\\Controller\\CreateMediaObjectAction'] = new \App\Controller\CreateMediaObjectAction();
    }
}
